controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

docs:
    path: /docs
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: '/public/docs/index.html.twig'
